/**
 * Marker-delimited managed block for the `/learn` memory topic: rendering is
 * pure and deterministic so `apply` is idempotent and unit-testable.
 * @module @dsh-cc/command-learn/render
 */

import type { Finding, ForensicsResult } from '@dsh-cc/session-forensics'

/** Memory topic slug owned by `/learn` (the file is `<name>.md`). */
export const TOPIC_NAME = 'session-learnings'

/** Memory frontmatter type for the learnings topic. */
export const TOPIC_TYPE = 'project' as const

/**
 * STABLE one-line description for the MEMORY.md pointer. Deliberately free of
 * finding counts or run dates: any per-run variance would churn the pointer
 * line on every apply (critic MUST-FIX). The run date lives in the body only.
 */
export const LEARNING_DESCRIPTION =
  'auto-distilled session failure corrections from /learn'

/** Managed block opening marker. */
export const BLOCK_START = '<!-- dsh-cc:learn:start -->'
/** Managed block closing marker. */
export const BLOCK_END = '<!-- dsh-cc:learn:end -->'

/** ISO date (YYYY-MM-DD) for the body header. */
export function isoDate(now: Date = new Date()): string {
  return now.toISOString().slice(0, 10)
}

/** Render one finding as deterministic markdown lines. */
export function renderFinding(finding: Finding): string[] {
  const lines = [`- **${finding.title}** (${finding.occurrences} occurrences)`]
  if (finding.detail.length > 0) lines.push(`  ${finding.detail}`)
  if (finding.evidence.length > 0) {
    lines.push(`  evidence: ${finding.evidence.slice(0, 3).join(', ')}`)
  }
  return lines
}

/**
 * Render the managed block for a forensics result. Deterministic for a given
 * result + date: the run date appears in the body header only, never in the
 * MEMORY.md pointer description.
 */
export function renderBlock(result: ForensicsResult, today: string): string {
  const lines = [
    BLOCK_START,
    '## Session Learnings',
    '*Auto-generated by /learn — do not edit manually*',
    '',
    `_Last run: ${today} — ${result.stats.sessionsScanned} session(s) scanned._`,
    '',
    ...result.findings.flatMap(renderFinding),
    BLOCK_END,
  ]
  return `${lines.join('\n')}\n`
}
